language: bash

addons:
  apt:
    packages:
      - gfortran
      - gcc
      - g++
      - expect

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y grace
  - sudo apt-get install -y libmotif-dev

install:
  - HEN_HOUSE/scripts/configure.expect linux.conf | tee configure.log

script:
  - pwd
  - for f in HEN_HOUSE/log/*.log configure.log; do echo $f; cat $f; done
  - (! grep -i fail configure.log)
  - '[ -f "$HOME/.config/EGSnrc/EGSnrc.bash" ] && . "$HOME/.config/EGSnrc/EGSnrc.bash"'
  - test -f "$EGS_CONFIG"
  - date
