EGSnrc C++ class library: EGS_BaseShape Class Reference
EGS_BaseShape Class Reference
Shapes | Main library
Base shape class. All shapes in the EGSnrc C++ class library are derived from EGS_BaseShape.
#include <egs_shapes.h>
Public Member Functions
EGS_BaseShape (const string &Name="", EGS_ObjectFactory *f=0)
Construct a shape named Name.
virtual ~EGS_BaseShape ()
Destructor. Deletes T if it is not null.
virtual EGS_Vector getRandomPoint (EGS_RandomGenerator *rndm)
Returns a random 3D vector.
virtual EGS_Vector getPoint (EGS_RandomGenerator *rndm)
Sample and return a random 3D vector.
void setTransformation (EGS_Input *inp)
Set the transformation attached to this shape.
void setTransformation (EGS_AffineTransform *t)
Set the transformation attached to this shape.
const EGS_AffineTransform * getTransform () const
Get a pointer to the affine transformation attached to this shape.
virtual bool supportsDirectionMethod () const
virtual void getNextShapePosition (EGS_RandomGenerator *rndm)
virtual void getPointSourceDirection (const EGS_Vector &xo, EGS_RandomGenerator *rndm, EGS_Vector &u, EGS_Float &wt)
virtual EGS_Float area () const
virtual void updatePosition (EGS_Float time)
Update the position of the shape if it is in motion.
Public Member Functions inherited from EGS_Object
EGS_Object (const string &Name="", EGS_ObjectFactory *f=0)
Create an EGS_Object named Name belonging to the object factory f.
EGS_Object (EGS_Input *inp, EGS_ObjectFactory *f=0)
Create an EGS_Object from the information pointed to by inp that belongs to object factory f.
const string & getObjectName () const
Get the object name.
void setObjectName (const string &Name)
Set the object name to Name.
const string & getObjectType () const
Get the object type.
virtual EGS_Object * createObject (EGS_Input *inp)
Create an object from the infromation pointed to by inp.
void setName (EGS_Input *inp)
Set the name of the object from the information provided by inp.
int ref ()
Increase the reference count to this object.
int deref ()
Decrease the reference count to this object.
void setFactory (EGS_ObjectFactory *f)
Set the factory to which the object belongs.
Static Public Member Functions
static EGS_BaseShape * createShape (EGS_Input *inp)
Create a shape from the information pointed to by inp.
static EGS_BaseShape * getShape (const string &Name)
Get a pointer to the shape named Name.
Static Public Member Functions inherited from EGS_Object
static string getUniqueName (const EGS_Object *o=0)
Create and return a unique object name.
static void deleteObject (EGS_Object *o)
Delete an object.
Protected Attributes
EGS_AffineTransform * T
The affine transformation attached to the shape.
Protected Attributes inherited from EGS_Object
string name
The object name.
string otype
The object type.
int nref
Number of references to the object.
EGS_ObjectFactory * factory
The factory this object belongs to.
Detailed Description
Base shape class. All shapes in the EGSnrc C++ class library are derived from EGS_BaseShape.
This class specifies the interface to shape objects. For more details on shapes, see the Shapes module documentation
Definition at line 114 of file egs_shapes.h.
Member Function Documentation
getRandomPoint()
virtual EGS_Vector EGS_BaseShape::getRandomPoint (EGS_RandomGenerator * rndm) virtual
Returns a random 3D vector.
Uses the virtual function getPoint() to pick a random position and then applies the affine transformation attached to the shape before returning it.
Reimplemented in EGS_DynamicShape.
Definition at line 136 of file egs_shapes.h.
Referenced by volcor::VCOptions::getRandomPoint().
getPoint()
virtual EGS_Vector EGS_BaseShape::getPoint (EGS_RandomGenerator * rndm) virtual
Sample and return a random 3D vector.
This virtual function must be reimplemented by derived classes to sample and return random positions from a certain probability distribution using the random number generator rndm.
Reimplemented in EGS_SphericalShellShape, EGS_DynamicShape, EGS_ConicalShellStackShape, EGS_CylinderShape, EGS_SphereShape, EGS_BoxShape, and EGS_PointShape.
Definition at line 151 of file egs_shapes.h.
References egsFatal.
setTransformation() [1/2]
void EGS_BaseShape::setTransformation (EGS_Input * inp)
Set the transformation attached to this shape.
If the input pointed to by inp contains a valid transformation definition, this function sets the affine transformation attached to the shape according to this definition.
See also
EGS_AffineTransform
Definition at line 69 of file egs_shapes.cpp.
References EGS_AffineTransform::getTransformation().
Referenced by EGS_DynamicShape::getNextShapePosition().
setTransformation() [2/2]
void EGS_BaseShape::setTransformation (EGS_AffineTransform * t)
Set the transformation attached to this shape.
The shape makes a copy of the transformation pointed to by t.
Definition at line 171 of file egs_shapes.h.
createShape()
EGS_BaseShape * EGS_BaseShape::createShape (EGS_Input * inp) static
Create a shape from the information pointed to by inp.
This static function creates a single shape from the input pointed to by inp. It returns a pointer to the newly created shape or null, if the information pointed to by inp was not sufficient to create a shape.
Definition at line 51 of file egs_shapes.cpp.
Referenced by EGS_CollimatedSource::EGS_CollimatedSource(), EGS_ParallelBeam::EGS_ParallelBeam(), EGS_GeometryTester::getGeometryTester(), and volcor::VCOptions::setBoundsShape().
getShape()
EGS_BaseShape * EGS_BaseShape::getShape (const string & Name) static
Get a pointer to the shape named Name.
A static list of shapes created so far is maintained internally. If a shape with name Name exists in this list, a pointer to this shape is returned. Otherwise the return value is null.
Definition at line 64 of file egs_shapes.cpp.
Referenced by EGS_CollimatedSource::EGS_CollimatedSource(), and EGS_ParallelBeam::EGS_ParallelBeam().
supportsDirectionMethod()
virtual bool EGS_BaseShape::supportsDirectionMethod () const virtual
Does this shape implement the getPointSourceDirection() method?
This virtual function should be re-implemented in derived classes if the shape supports the getPointSourceDirection() method.
Reimplemented in EGS_SphericalShellShape, EGS_DynamicShape, EGS_CylinderShape, EGS_SphereShape, EGS_BoxShape, and EGS_SurfaceShape.
Definition at line 206 of file egs_shapes.h.
Referenced by EGS_CollimatedSource::EGS_CollimatedSource(), and EGS_DynamicShape::supportsDirectionMethod().
getPointSourceDirection()
virtual void EGS_BaseShape::getPointSourceDirection (const EGS_Vector & xo, EGS_RandomGenerator * rndm, EGS_Vector & u, EGS_Float & wt) virtual
Get a random direction given a source position xo.
This method is used to sample random directions by picking a point randomly on a certain surface and then setting the direction to . This is useful for simulating a point source collimated to a certain solid angle as defined by the surface from which the points are picked. The method should be re-implemented by shapes being able to pick surface points and to properly set the statistical weight wt so that a proper collimated point source probability distribution results.
Reimplemented in EGS_SphericalShellShape, EGS_DynamicShape, EGS_CylinderShape, EGS_SphereShape, EGS_BoxShape, and EGS_SurfaceShape.
Definition at line 230 of file egs_shapes.h.
References egsFatal.
area()
virtual EGS_Float EGS_BaseShape::area () const virtual
Get the area of this shape.
This method should be re-implemented by surface shapes to return their area. It is used by some of the particle sources to define fluence as the number of particles per unit area.
Reimplemented in EGS_SphericalShellShape, EGS_CylinderShape, EGS_SphereShape, EGS_BoxShape, and EGS_SurfaceShape.
Definition at line 242 of file egs_shapes.h.
The documentation for this class was generated from the following files:
/home/rwtownson/EGSnrc/HEN_HOUSE/egs++/egs_shapes.h
/home/rwtownson/EGSnrc/HEN_HOUSE/egs++/egs_shapes.cpp