EGSnrc C++ class library: EGS_ParallelBeam Class Reference
EGS_ParallelBeam Class Reference
Particle sources
A parallel beam.
#include <egs_parallel_beam.h>
Public Member Functions
EGS_ParallelBeam (int Q, EGS_BaseSpectrum *Spec, EGS_BaseShape *Shape, const string &Name="", EGS_ObjectFactory *f=0)
Constructor.
EGS_ParallelBeam (EGS_Input *, EGS_ObjectFactory *f=0)
Constructor.
void getPositionDirection (EGS_RandomGenerator *rndm, EGS_Vector &x, EGS_Vector &u, EGS_Float &wt)
EGS_Float getFluence () const
bool storeFluenceState (ostream &) const
bool setFluenceState (istream &)
bool isValid () const
Public Member Functions inherited from EGS_BaseSimpleSource
EGS_BaseSimpleSource (int Q, EGS_BaseSpectrum *Spec, const string &Name="", EGS_ObjectFactory *f=0)
Constructor.
EGS_BaseSimpleSource (EGS_Input *input, EGS_ObjectFactory *f=0)
Construct a 'simple' particle source from the information pointed to by input.
~EGS_BaseSimpleSource ()
Destructor.
virtual EGS_I64 getNextParticle (EGS_RandomGenerator *rndm, int &Q, int &latch, EGS_Float &E, EGS_Float &wt, EGS_Vector &x, EGS_Vector &u)
Sample the next source particle from the source probability distribution.
virtual EGS_Float getEmax () const
Get the maximum energy of the source.
int getCharge () const
Get the charge of the source.
virtual bool storeState (ostream &data_out) const
Store the source state to the data stream data_out.
virtual bool addState (istream &data)
Add the source state from the stream data to the current state.
virtual void resetCounter ()
Reset the source to a state with zero sampled particles.
virtual bool addFluenceData (istream &data)
Add fluence data from the stream data to the current state.
virtual void resetFluenceCounter ()
Reset the data related to the sampling of positions and directions to a state with zero sampled particles.
virtual bool setState (istream &data)
Set the source state according to the data in the stream data.
Public Member Functions inherited from EGS_BaseSource
EGS_BaseSource (const string &Name="", EGS_ObjectFactory *f=0)
Construct a source named Name.
EGS_BaseSource (EGS_Input *input, EGS_ObjectFactory *f=0)
Construct a source from the input pointed to by inp.
const char * getSourceDescription () const
Get a short description of this source.
virtual void setSimulationChunk (EGS_I64 nstart, EGS_I64 nrun, int npar, int nchunk)
Set the next simulation chunk to start at nstart and to consist of nrun particles.
virtual void printSampledEmissions ()
Print statistics on what was sampled from the source.
virtual vector< EGS_Ensdf * > getRadionuclideEnsdf ()
Get the radionuclide ENSDF object from the source.
EGS_Float getTimeIndex ()
void setTimeIndex (EGS_Float temp_time)
virtual void containsDynamic (bool &hasdynamic)
Public Member Functions inherited from EGS_Object
EGS_Object (const string &Name="", EGS_ObjectFactory *f=0)
Create an EGS_Object named Name belonging to the object factory f.
EGS_Object (EGS_Input *inp, EGS_ObjectFactory *f=0)
Create an EGS_Object from the information pointed to by inp that belongs to object factory f.
const string & getObjectName () const
Get the object name.
void setObjectName (const string &Name)
Set the object name to Name.
const string & getObjectType () const
Get the object type.
virtual EGS_Object * createObject (EGS_Input *inp)
Create an object from the infromation pointed to by inp.
void setName (EGS_Input *inp)
Set the name of the object from the information provided by inp.
int ref ()
Increase the reference count to this object.
int deref ()
Decrease the reference count to this object.
void setFactory (EGS_ObjectFactory *f)
Set the factory to which the object belongs.
Protected Member Functions
void setUp ()
Protected Member Functions inherited from EGS_BaseSimpleSource
virtual void setLatch (int &latch)
Protected Attributes
EGS_BaseShape * shape
The shape.
EGS_Vector uo
The direction of the particles.
Protected Attributes inherited from EGS_BaseSimpleSource
int q
The charge of this simple source.
EGS_BaseSpectrum * s
The energy spectrum of this source.
string type
A short description of the source type.
EGS_I64 count
Number of statistically independent particles delivered so far.
Protected Attributes inherited from EGS_BaseSource
string description
A short source description.
EGS_Float time_index
time index corresponding to a particle. This stores the current time index for all objects in the simulation (with the potential exception of beam and iaea_phsp source)
Protected Attributes inherited from EGS_Object
string name
The object name.
string otype
The object type.
int nref
Number of references to the object.
EGS_ObjectFactory * factory
The factory this object belongs to.
Additional Inherited Members
Static Public Member Functions inherited from EGS_BaseSource
static EGS_BaseSource * createSource (EGS_Input *)
Create sources from the information pointed to by input.
static EGS_BaseSource * getSource (const string &Name)
Get a pointer to the source named Name.
static void addKnownSource (EGS_BaseSource *o)
Add a known source object to the source factory.
static void addKnownTypeId (const char *name)
Add a known source object typeid to the source factory.
Static Public Member Functions inherited from EGS_Object
static string getUniqueName (const EGS_Object *o=0)
Create and return a unique object name.
static void deleteObject (EGS_Object *o)
Delete an object.
Detailed Description
A parallel beam.
A parallel beam is a source that delivers particles all having the same direction with a position within any shape. Although planar shapes would make more sense for a parallel beam, due to the abstract nature of shapes, any shape can be used. A parallel beam is defined as follows:
:start source:
    library = egs_parallel_beam
    name = some_name
    :start shape:
        definition of the shape
    :stop shape:
    :start spectrum:
        definition of the spectrum
    :stop spectrum:
    direction = Ux Uy Uz
    charge = -1 or 0 or 1 for electrons or photons or positrons
:stop source:
It is worth noting that the functionality of sources 0, 2, 10 and 13 from the RZ series of user codes and sources 0 and 1 in DOSXYZnrc can be reproduced with the parallel beam source from the EGSnrc C++ class library.
A simple example:
:start source definition:
    :start source:
        library = egs_parallel_beam
        name = my_source
        :start shape:
            type = cylinder
            radius   = 1
            height   = 2
            axis     = 0 0 1
            midpoint = 0
        :stop shape:
        direction = 0 0 1
        charge = 0
        :start spectrum:
            type = monoenergetic
            energy = 6
        :stop spectrum:
    :stop source:
    simulation source = my_source
:stop source definition:
A simple example
Definition at line 125 of file egs_parallel_beam.h.
Constructor & Destructor Documentation
EGS_ParallelBeam() [1/2]
EGS_ParallelBeam::EGS_ParallelBeam (int Q, EGS_BaseSpectrum * Spec, EGS_BaseShape * Shape, const string & Name = "", EGS_ObjectFactory * f = 0)
Constructor.
Construct a parallel beam with charge Q and spectrum Spec from a shape Shape
Definition at line 135 of file egs_parallel_beam.h.
EGS_ParallelBeam() [2/2]
EGS_ParallelBeam::EGS_ParallelBeam (EGS_Input * input, EGS_ObjectFactory * f = 0)
Constructor.
Construct a parallel beam from the information pointed to by inp.
Definition at line 40 of file egs_parallel_beam.cpp.
References EGS_BaseShape::createShape(), egsWarning, epsilon, EGS_Input::getInput(), EGS_BaseShape::getShape(), shape, EGS_Input::takeInputItem(), uo, EGS_Vector::x, EGS_Vector::y, and EGS_Vector::z.
The documentation for this class was generated from the following files:
/home/rwtownson/EGSnrc/HEN_HOUSE/egs++/sources/egs_parallel_beam/egs_parallel_beam.h
/home/rwtownson/EGSnrc/HEN_HOUSE/egs++/sources/egs_parallel_beam/egs_parallel_beam.cpp